### ISSUE TITLE
bug on pregnancy lens?

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/pregnancy-lens#1]
### Test Lens: Pregnancy
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/processedbundledovato-en?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy&patientIdentifier=Pedro-1

### that worked
POST https://gravitate-health.lst.tfo.upm.es/focusing/focus/bundlepackageleaflet-en-49178f16170ee8a6bc2a4361c1748d5f?preprocessors=preprocessing-service-manual&lenses=lens-selector-mvp2_pregnancy-collapse&patientIdentifier=Pedro-1

both should work right?

**Comment by aalonsolopez** [comment]
@joofio pregnancy-collapse lens doesn't exist

**Comment by joofio** [comment]
🤦

Alejandro Alonso López ***@***.***> escreveu (terça,
16/07/2024 à(s) 11:37):

**Comment by joofio** [comment]
no issue: https://gravitate-health.lst.tfo.upm.es/focusing/focus/processedbundlekarveabik?preprocessors=preprocessing-service-manual&lenses=pregnancy-lens&patientIdentifier=Pedro-1 works
sorry
